export const allProperties = [
    {
        id: "1",
        title: "Nowoczesny Penthouse Szklany",
        location: "Warszawa, Centrum",
        price: "4 250 000 PLN",
        sqm: 145,
        beds: 3,
        baths: 2,
        image: "/assets/demos/nieruchomosci/penthouse-new.png",
        type: "Apartament",
        status: "Sprzedaż",
        description: "Wyjątkowy penthouse w samym sercu Warszawy. Przeszklone ściany oferują zapierający dech w piersiach widok na panoramę miasta. Wykończony materiałami najwyższej klasy - marmur, dąb i stal szczotkowana.",
        features: ["Smart Home", "Prywatny taras", "Klimatyzacja", "Ochrona 24h", "2 miejsca postojowe"],
        yearBuilt: 2023,
        energyClass: "A++"
    },
    {
        id: "2",
        title: "Luksusowa Rezydencja nad Jeziorem",
        location: "Mazury, Giżycko",
        price: "6 800 000 PLN",
        sqm: 320,
        beds: 5,
        baths: 4,
        image: "/assets/demos/nieruchomosci/lakeview-new.png",
        type: "Willa",
        status: "Sprzedaż",
        description: "Imponująca posiadłość nad samym jeziorem. Architektura wtapiająca się w naturę, własna linia brzegowa z pomostem. Dom wyposażony w systemy odnawialnej energii i prywatną strefę spa.",
        features: ["Linia brzegowa", "Pomost", "Basen infinity", "Panele fotowoltaiczne", "Garaż na 3 auta"],
        yearBuilt: 2022,
        energyClass: "A"
    },
    {
        id: "3",
        title: "Rezydencja Skyline",
        location: "Wrocław, Sky Tower",
        price: "3 100 000 PLN",
        sqm: 98,
        beds: 2,
        baths: 2,
        image: "/assets/demos/nieruchomosci/skyline-new.png",
        type: "Apartament",
        status: "Sprzedaż",
        description: "Luksusowy apartament na wysokim piętrze ikonicznego budynku. Nowoczesny design, dostęp do usług hotelowych i strefy wellness w budynku.",
        features: ["Widok na miasto", "Concierge", "Siłownia", "Basen", "Klimatyzacja"],
        yearBuilt: 2021,
        energyClass: "B"
    },
    {
        id: "4",
        title: "Industrialny Loft w Centrum",
        location: "Kraków, Kazimierz",
        price: "2 450 000 PLN",
        sqm: 115,
        beds: 2,
        baths: 1,
        image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
        type: "Loft",
        status: "Sprzedaż",
        description: "Charakterystyczny loft w sercu artystycznej dzielnicy Kazimierz. Wysokie sufity, odsłonięte cegły i stalowe belki tworzą unikalny klimat industrialny. Idealne miejsce dla miłośników sztuki i kultury.",
        features: ["Wysokość 4.5m", "Odsłonięta cegła", "Duże okna", "Parking podziemny", "Art gallery w budynku"],
        yearBuilt: 2020,
        energyClass: "B+"
    },
    {
        id: "5",
        title: "Apartament Premium nad Morzem",
        location: "Gdynia, Orłowo",
        price: "3 650 000 PLN",
        sqm: 128,
        beds: 3,
        baths: 2,
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
        type: "Apartament",
        status: "Sprzedaż",
        description: "Ekskluzywny apartament z widokiem na Zatokę Gdańską. Położony zaledwie 100m od promenady i plaży. Przestronny taras idealny do porannych nawyków przy dźwiękach morza.",
        features: ["Widok na morze", "Taras 30m²", "Sauna", "Kominek", "Miejsce postojowe"],
        yearBuilt: 2023,
        energyClass: "A"
    },
    {
        id: "6",
        title: "Górska Willa Wypoczynkowa",
        location: "Zakopane, Gubałówka",
        price: "5 200 000 PLN",
        sqm: 245,
        beds: 4,
        baths: 3,
        image: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=800&q=80",
        type: "Willa",
        status: "Sprzedaż",
        description: "Luksusowa górska rezydencja z panoramicznym widokiem na Tatry. Architektura łącząca tradycyjny styl góralski z nowoczesnymi rozwiązaniami. Idealny wypoczynek przez cały rok.",
        features: ["Widok na Tatry", "Kominek", "Sauna fińska", "Ogród zimowy", "Garaż podwójny"],
        yearBuilt: 2022,
        energyClass: "A+"
    },
    {
        id: "7",
        title: "Luksusowy Penthouse Centrum",
        location: "Warszawa, Powiśle",
        price: "15 000 PLN / miesiąc",
        sqm: 180,
        beds: 3,
        baths: 2,
        image: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80",
        type: "Apartament",
        status: "Wynajem",
        description: "Spektakularny penthouse w ekskluzywnej lokalizacji. Panoramiczne okna z widokiem na Wisłę i centrum miasta. Wykończenie najwyższej klasy, w pełni wyposażony, gotowy do wprowadzenia.",
        features: ["Widok na Wisłę", "Taras 50m²", "2 miejsca parkingowe", "Klimatyzacja", "Concierge 24h"],
        yearBuilt: 2023,
        energyClass: "A++"
    },
    {
        id: "8",
        title: "Apartament Nadmorski Premium",
        location: "Sopot, Molo",
        price: "8 500 PLN / miesiąc",
        sqm: 95,
        beds: 2,
        baths: 1,
        image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
        type: "Apartament",
        status: "Wynajem",
        description: "Nowoczesny apartament zaledwie 100m od mola i plaży. Stylowe wnętrze w morskim klimacie, duży balkon z widokiem na morze. Idealne miejsce dla miłośników nadmorskiego stylu życia.",
        features: ["Widok na morze", "Balkon", "Umeblowany", "Internet światłowodowy", "Parking podziemny"],
        yearBuilt: 2021,
        energyClass: "A"
    }
];
